code --install-extension aaron-bond.better-comments
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension foxundermoon.shell-format
code --install-extension jasonnutter.vscode-codeowners
code --install-extension jock.svg
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension magicstack.MagicPython
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-json5
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension naumovs.color-highlight
code --install-extension octref.vetur
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension sburg.vscode-javascript-booster
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-polish
code --install-extension streetsidesoftware.code-spell-checker-swedish
code --install-extension styled-components.vscode-styled-components
code --install-extension syler.sass-indented
code --install-extension thomas-baumgaertner.vcl
code --install-extension tomoki1207.pdf
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension VisualStudioExptTeam.vscodeintellicode-completions
code --install-extension VisualStudioExptTeam.vscodeintellicode-insiders
code --install-extension vscode-icons-team.vscode-icons
code --install-extension Vtrois.gitmoji-vscode
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
